kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-radarr-config
  namespace: radarr
  labels:
    app: radarr
spec:
  storageClassName: "longhorn"
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "2Gi"