apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "homelab.fullname" . }}
  labels:
    {{- include "homelab.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  strategy:
    {{- toYaml .Values.strategy | nindent 4 }}
  selector:
    matchLabels:
      {{- include "homelab.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "homelab.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "homelab.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.uiContainerPort }}
              protocol: TCP
            - name: wg-port
              containerPort: {{ .Values.uiContainerPort }}
              protocol: UDP
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 60
            failureThreshold: 5
            timeoutSeconds: 10
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 60
            failureThreshold: 5
            timeoutSeconds: 10
          env:
            {{- if .Values.env.password }}
            - name: PASSWORD
              value: {{ .Values.env.password }}
            {{- end }}
            {{- if .Values.env.wg_host }}
            - name: WG_HOST
              value: {{ .Values.env.wg_host }}
            {{- end }}
            {{- if .Values.env.wg_port }}
            - name: WG_PORT
              value: {{ .Values.env.wg_port }}
            {{- end }}
            {{- if .Values.env.wg_mtu }}
            - name: WG_MTU
              value: {{ .Values.env.wg_mtu }}
            {{- end }}
            {{- if .Values.env.wg_persistent_keepalive }}
            - name: WG_PERSISTENT_KEEPALIVE
              value: {{ .Values.env.wg_persistent_keepalive }}
            {{- end }}
            {{- if .Values.env.wg_default_address }}
            - name: WG_DEFAULT_ADDRESS
              value: {{ .Values.env.wg_default_address }}
            {{- end }}   
            {{- if .Values.env.wg_default_dns }}
            - name: WG_DEFAULT_DNS
              value: {{ .Values.env.wg_default_dns }}
            {{- end }} 
            {{- if .Values.env.wg_allowed_ips }}
            - name: WG_ALLOWED_IPS
              value: {{ .Values.env.wg_allowed_ips }}
            {{- end }} 
            {{- if .Values.env.wg_post_up }}
            - name: WG_POST_UP
              value: {{ .Values.env.wg_post_up }}
            {{- end }} 
            {{- if .Values.env.wg_post_down }}
            - name: WG_POST_DOWN
              value: {{ .Values.env.wg_post_down }}
            {{- end }}         
          volumeMounts:
            - mountPath: /etc/wireguard
              name: config
              {{- if .Values.persistentVolumeClaimConfig.subPath }}
              subPath: {{ .Values.persistentVolumeClaimConfig.subPath }}
              {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: config
        {{- if .Values.persistentVolumeClaimConfig.enabled }}
        persistentVolumeClaim:
          claimName: {{ if .Values.persistentVolumeClaimConfig.existingClaim }}{{ .Values.persistentVolumeClaimConfig.existingClaim }}{{- else }}pvc-{{ template "homelab.fullname" . }}-config{{- end }}
        {{- else if .Values.customVolumesConfig.enabled }}
{{- toYaml .Values.customVolumesConfig.config | nindent 8 }}
        {{- else }}
        emptyDir: {}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
