apiVersion: v1
kind: Service
metadata:
  name: {{ include "homelab.fullname" . }}-wg
  labels:
    {{- include "homelab.labels" . | nindent 4 }}
spec:
  type: {{ .Values.serviceWireguard.type }}
  ports:
    - port: {{ .Values.serviceWireguard.port }}
      targetPort: wg-port
      protocol: UDP
      name: wg-port
  selector:
    {{- include "homelab.selectorLabels" . | nindent 4 }}
