{{- if .Values.persistentVolumeClaimConfig.enabled -}}
{{- if not .Values.persistentVolumeClaimConfig.existingClaim -}}
apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
{{- if .Values.persistentVolumeClaimConfig.annotations }}
  annotations:
{{ toYaml .Values.persistentVolumeClaimConfig.annotations | indent 4 }}
{{- end }}
  labels:
    app: {{ template "homelab.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.persistentVolumeClaimConfig.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: pvc-{{ template "homelab.fullname" . }}-config
spec:
  accessModes:
{{ toYaml .Values.persistentVolumeClaimConfig.accessModes | indent 4 }}
{{- if .Values.persistentVolumeClaimConfig.storageClass }}
{{- if (eq "-" .Values.persistentVolumeClaimConfig.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.persistentVolumeClaimConfig.storageClass }}"
{{- end }}
{{- end }}
  resources:
    requests:
      storage: "{{ .Values.persistentVolumeClaimConfig.size }}"
{{- end -}}
{{- end -}}